# Generated by Django 6.0.3 on 2026-03-22 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('category', models.CharField(choices=[('language', 'Language'), ('os', 'OS'), ('software', 'Software'), ('network', 'Network'), ('hardware', 'Hardware'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('technology', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bugs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='bugs.bug')),
            ],
            options={
                'db_table': 'bug_snippets',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BugTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.bug')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.tag')),
            ],
            options={
                'db_table': 'bug_tags',
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bugs', through='bugs.BugTag', to='bugs.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tags_user_id_eb4e0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bugtag',
            unique_together={('bug', 'tag')},
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['user', 'status'], name='bugs_user_id_011f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['user', 'severity'], name='bugs_user_id_059217_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['user', 'category'], name='bugs_user_id_77a69a_idx'),
        ),
    ]
